"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url


# ---------------------------------------------------------------------
# LOAD ENVIRONMENT VARIABLES
# ---------------------------------------------------------------------

# Load env.py during local development if it exists.
if os.path.isfile("env.py"):
    import env


# ---------------------------------------------------------------------
# BASE DIRECTORY
# ---------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------
# SECURITY / DEVELOPMENT
# ---------------------------------------------------------------------

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "default-secret-key",
)

DEBUG = os.environ.get("DEVELOPMENT", "False") == "True"


ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]


# ---------------------------------------------------------------------
# APPLICATIONS
# ---------------------------------------------------------------------

INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",

    # Django Allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",

    # Local apps
    "home",
    'bespoke.apps.BespokeConfig',
    "orders",
    "shop",
]


SITE_ID = 1


# ---------------------------------------------------------------------
# MIDDLEWARE
# ---------------------------------------------------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # Required by Django Allauth
    "allauth.account.middleware.AccountMiddleware",
]


# ---------------------------------------------------------------------
# URL CONFIGURATION
# ---------------------------------------------------------------------

ROOT_URLCONF = "core.urls"


# ---------------------------------------------------------------------
# TEMPLATES
# ---------------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates",
        ],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ---------------------------------------------------------------------
# WSGI
# ---------------------------------------------------------------------

WSGI_APPLICATION = "core.wsgi.application"


# ---------------------------------------------------------------------
# DATABASE
# ---------------------------------------------------------------------

DATABASES = {
    "default": dj_database_url.parse(
        os.environ.get("DATABASE_URL")
    )
}


# ---------------------------------------------------------------------
# PASSWORD VALIDATION
# ---------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ---------------------------------------------------------------------
# INTERNATIONALISATION
# ---------------------------------------------------------------------

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# ---------------------------------------------------------------------
# STATIC FILES
# ---------------------------------------------------------------------

# URL used when referring to static files.
STATIC_URL = "/static/"


# Main project static directory.
#
# Example:
#
# static/
# ├── css/
# │   └── style.css
# ├── js/
# └── media/
#     └── logo-I.png
#
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Destination used by:
#
# python manage.py collectstatic
#
# Do NOT manually store your CSS/images in here.
STATIC_ROOT = BASE_DIR / "staticfiles"


# ---------------------------------------------------------------------
# EMAIL
# Django 6.1 MAILERS configuration
# ---------------------------------------------------------------------

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.smtp.EmailBackend",

        "OPTIONS": {
            "host": "smtp.gmail.com",

            "port": 587,

            "username": os.environ.get(
                "EMAIL_HOST_USER"
            ),

            "password": os.environ.get(
                "EMAIL_HOST_PASSWORD"
            ),

            "use_tls": True,

            "timeout": 10,
        },
    },
}


DEFAULT_FROM_EMAIL = os.environ.get(
    "EMAIL_HOST_USER",
    "donotreplyk61@gmail.com",
)


# ---------------------------------------------------------------------
# DJANGO ALLAUTH
# ---------------------------------------------------------------------

# Fields displayed on the signup page.
#
# The * means the field is required.
ACCOUNT_SIGNUP_FIELDS = [
    "username*",
    "email*",
    "password1*",
    "password2*",
]


# ---------------------------------------------------------------------
# EMAIL VERIFICATION
# ---------------------------------------------------------------------

# Email verification is REQUIRED.
# Users cannot log in until they have verified their email address.
ACCOUNT_EMAIL_VERIFICATION = "mandatory"


# False = send the customer a clickable verification link.
# True = send them a verification code instead.
ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = False


# Verification links expire after 3 days.
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3


# Automatically log the customer in after they successfully
# verify their email address.
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True


# Prefix used on Allauth emails.
# Example:
# [K9] Please Confirm Your Email Address
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[K9] "


# After a normal uninterrupted signup.
#
# Note: when mandatory email verification is enabled, Allauth
# interrupts the normal signup redirect and sends the customer
# through the verification process first.
ACCOUNT_SIGNUP_REDIRECT_URL = "signup_complete"


# After successful email verification, send an authenticated
# customer to our signup complete page.
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "signup_complete"


# ---------------------------------------------------------------------
# AUTHENTICATION REDIRECTS
# ---------------------------------------------------------------------

# Where to send users after signing in.
LOGIN_REDIRECT_URL = "/"


# Where to send users after signing out.
LOGOUT_REDIRECT_URL = "/"