# Generated by Django 6.1 on 2026-09-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BespokeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('item_type', models.CharField(help_text='e.g., Custom Engraved Plaque, Pet Memorial, Custom Gift Box', max_length=150)),
                ('description', models.TextField(help_text='Describe your custom vision, dimensions, or specific requirements.')),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
