# Generated by Django 6.1 on 2026-09-19 06:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bespoke', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bespokerequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='attachment_notes',
            field=models.TextField(blank=True, help_text='Reserved for notes relating to future customer attachments.'),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='avoid',
            field=models.TextField(blank=True, help_text='Anything the customer definitely does not want.'),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='best_contact_time',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='budget_flexible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='colours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='contact_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='deadline_flexible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='delivery_postcode',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='details_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='finish_notes',
            field=models.TextField(blank=True, help_text='Finish, texture, mounting, display, packaging or other visual requirements.'),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='fulfilment',
            field=models.CharField(choices=[('post', 'Post / Courier'), ('collection', 'Collection'), ('discuss', 'Not Sure Yet')], default='discuss', max_length=20),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='inspiration_source',
            field=models.CharField(blank=True, help_text='For example: a memory, hobby, pet, place, photograph, theme or existing item.', max_length=200),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='materials',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='must_include',
            field=models.TextField(blank=True, help_text='Anything that absolutely must be included.'),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='needed_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='occasion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='occasion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='personalisation_text',
            field=models.TextField(blank=True, help_text='Names, dates, wording, quotes or messages to appear on the finished item.'),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='practical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('either', 'Either')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='recipient_age',
            field=models.CharField(blank=True, help_text='An exact age or approximate range is fine.', max_length=40),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='recipient_interests',
            field=models.TextField(blank=True, help_text='Hobbies, interests, favourite things, personality or anything that may help with the design.'),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='recipient_relationship',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='request_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='size_or_dimensions',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewing', 'Under Review'), ('more_info', 'More Information Needed'), ('quoted', 'Quote Sent'), ('accepted', 'Quote Accepted'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('completed', 'Completed'), ('declined', 'Unable to Fulfil'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='story_or_meaning',
            field=models.TextField(blank=True, help_text='Any story, memory or meaning behind the gift.'),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='style',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='theme',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bespokerequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bespoke_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bespokerequest',
            name='description',
            field=models.TextField(blank=True, help_text='Describe your idea, vision, dimensions, requirements or anything else you have in mind.'),
        ),
        migrations.AlterField(
            model_name='bespokerequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='bespokerequest',
            name='item_type',
            field=models.CharField(blank=True, help_text='For example: plaque, memorial, gift box, sign, keepsake, decoration or something completely unique.', max_length=150),
        ),
        migrations.AlterField(
            model_name='bespokerequest',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='BespokeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bespoke/attachments/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bespoke.bespokerequest')),
            ],
            options={
                'ordering': ['sort_order', 'uploaded_at'],
            },
        ),
    ]
