# Generated by Django 6.1 on 2026-09-19 06:45

import bespoke.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bespoke', '0002_alter_bespokerequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bespokerequest',
            name='reference',
            field=models.CharField(default=bespoke.models.generate_bespoke_reference, editable=False, max_length=16, unique=True),
        ),
    ]
