# Generated by Django 6.1 on 2026-09-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_total_order_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent / Complete'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
