# Generated by Django 6.1 on 2026-09-19 13:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bespoke', '0004_bespokenotificationpreference'),
        ('orders', '0003_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='bespoke_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bespoke.bespokerequest'),
        ),
        migrations.CreateModel(
            name='BespokeOrderWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveSmallIntegerField(choices=[(1, 'Job Overview'), (2, 'Customer Contact'), (3, 'Design & Specification'), (4, 'Pricing & Quote'), (5, 'Approval & Payment'), (6, 'Production'), (7, 'Completion & Delivery'), (8, 'Close Job')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('stage', models.CharField(choices=[('new', 'New Job'), ('review', 'Staff Review'), ('customer_contact', 'Customer Contact'), ('design', 'Design & Specification'), ('quote', 'Pricing & Quote'), ('awaiting_customer', 'Awaiting Customer'), ('approved', 'Customer Approved'), ('payment', 'Payment'), ('production', 'Production'), ('ready', 'Ready'), ('delivery', 'Delivery / Collection'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='new', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('staff_summary', models.TextField(blank=True, help_text='Short staff summary of the current position of this bespoke job.')),
                ('next_action', models.TextField(blank=True, help_text='What needs to happen next?')),
                ('next_action_due', models.DateTimeField(blank=True, null=True)),
                ('customer_waiting', models.BooleanField(default=False, help_text='Tick when K9 is waiting for the customer to respond.')),
                ('customer_waiting_since', models.DateTimeField(blank=True, null=True)),
                ('on_hold_reason', models.TextField(blank=True)),
                ('last_worked_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bespoke_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bespoke_workflows', to=settings.AUTH_USER_MODEL)),
                ('last_worked_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_worked_bespoke_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bespoke_workflow', to='orders.order')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('in_person', 'In Person'), ('other', 'Other')], default='email', max_length=20)),
                ('direction', models.CharField(choices=[('incoming', 'Customer to K9'), ('outgoing', 'K9 to Customer')], default='outgoing', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('received', 'Received'), ('logged', 'Logged'), ('failed', 'Failed')], default='logged', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('from_address', models.EmailField(blank=True, max_length=254)),
                ('to_address', models.EmailField(blank=True, max_length=254)),
                ('summary', models.CharField(blank=True, help_text='Short description shown in the communication timeline.', max_length=500)),
                ('content', models.TextField(blank=True, help_text='Email body, phone call notes or other communication details.')),
                ('has_attachment', models.BooleanField(default=False)),
                ('attachment_names', models.JSONField(blank=True, default=list, help_text='Names of files exchanged by email. The actual files are not stored here.')),
                ('attachment_notes', models.TextField(blank=True, help_text='Optional notes about files or pictures supplied separately by email.')),
                ('message_id', models.CharField(blank=True, help_text='Optional email Message-ID for future email tracking.', max_length=255)),
                ('thread_reference', models.CharField(blank=True, help_text='Optional external email thread/reference.', max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the email, phone call or other communication actually occurred.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_communications', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='orders.order')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
    ]
