# Generated by Django 6.1 on 2026-09-19 14:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_order_bespoke_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercommunication',
            name='context',
            field=models.CharField(choices=[('general', 'General'), ('contact', 'Customer Contact'), ('design', 'Design'), ('quote', 'Quote'), ('approval', 'Approval'), ('payment', 'Payment'), ('production', 'Production'), ('delivery', 'Delivery')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='bespokeorderworkflow',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bespoke_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bespokeorderworkflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bespoke_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bespokeorderworkflow',
            name='customer_waiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bespokeorderworkflow',
            name='last_worked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recent_bespoke_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bespokeorderworkflow',
            name='next_action',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bespokeorderworkflow',
            name='staff_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ordercommunication',
            name='attachment_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ordercommunication',
            name='attachment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordercommunication',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone'), ('in_person', 'In Person'), ('other', 'Other')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordercommunication',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordercommunication',
            name='direction',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordercommunication',
            name='from_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ordercommunication',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_order_communications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordercommunication',
            name='message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ordercommunication',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ordercommunication',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordercommunication',
            name='thread_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ordercommunication',
            name='to_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='k9_order_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BespokeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('courier', 'Courier'), ('post', 'Post'), ('collection', 'Customer Collection'), ('local_delivery', 'Local Delivery')], max_length=30)),
                ('status', models.CharField(choices=[('not_ready', 'Not Ready'), ('ready', 'Ready'), ('dispatched', 'Dispatched'), ('collected', 'Collected'), ('delivered', 'Delivered')], default='not_ready', max_length=20)),
                ('carrier', models.CharField(blank=True, max_length=100)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=150)),
                ('dispatch_notes', models.TextField(blank=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_bespoke_jobs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bespoke_deliveries', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_record', to='orders.bespokeorderworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='BespokeDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('final_design_summary', models.TextField(blank=True)),
                ('final_design_ready', models.BooleanField(default=False)),
                ('final_design_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bespoke_designs', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design_record', to='orders.bespokeorderworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='BespokeProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_production_jobs', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_record', to='orders.bespokeorderworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='BespokeQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('superseded', 'Superseded'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('title', models.CharField(default='Bespoke Quote', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bespoke_quotes', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='orders.bespokeorderworkflow')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='BespokeApprovalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('approval_requested_at', models.DateTimeField(blank=True, null=True)),
                ('customer_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_name', models.CharField(blank=True, max_length=150)),
                ('approved_email', models.EmailField(blank=True, max_length=254)),
                ('approval_notes', models.TextField(blank=True)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('awaiting_approval', 'Awaiting Customer Approval'), ('awaiting_payment', 'Awaiting Payment'), ('processing', 'Payment Processing'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='not_ready', max_length=30)),
                ('payment_provider', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('checkout_reference', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_payment', to='orders.bespokeorderworkflow')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_records', to='orders.bespokequote')),
            ],
        ),
        migrations.CreateModel(
            name='BespokeQuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.bespokequote')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='bespokequote',
            constraint=models.UniqueConstraint(fields=('workflow', 'version'), name='unique_bespoke_quote_version'),
        ),
    ]
