# Generated by Django 6.1 on 2026-09-19 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordercommunication_context_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BespokeDesignVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, help_text='Optional short title for this design version.', max_length=200)),
                ('customer_summary', models.TextField(help_text='Description of this design version shown to the customer.')),
                ('change_summary', models.TextField(blank=True, help_text='Explain what changed from the previous version.')),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes. Never shown to the customer.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Customer'), ('accepted', 'Accepted'), ('rejected', 'Rejected / Changes Requested'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=20)),
                ('response_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_content_type', models.CharField(blank=True, max_length=150)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('file_sha256', models.CharField(blank=True, max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_name', models.CharField(blank=True, max_length=200)),
                ('response_email', models.EmailField(blank=True, max_length=254)),
                ('response_notes', models.TextField(blank=True, help_text='Customer comments or requested changes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bespoke_design_versions_created', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='orders.bespokedesign')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bespoke_design_versions_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='ordercommunication',
            name='design_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='orders.bespokedesignversion'),
        ),
        migrations.AddConstraint(
            model_name='bespokedesignversion',
            constraint=models.UniqueConstraint(fields=('design', 'version'), name='unique_bespoke_design_version'),
        ),
    ]
