# Generated by Django 6.1 on 2026-09-20 13:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_bespokedesignversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bespokequote',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='bespokequote',
            name='vat_enabled',
            field=models.BooleanField(default=False, help_text='Enable VAT calculation for this quote.'),
        ),
        migrations.AddField(
            model_name='bespokequote',
            name='vat_on_delivery',
            field=models.BooleanField(default=True, help_text='Include the delivery charge when calculating VAT.'),
        ),
        migrations.AddField(
            model_name='bespokequote',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='VAT percentage entered by staff.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
